server.port=${SERVER_PORT:5008}

backend.base-url=${BACKEND_BASE_URL:http://localhost:5007/api/v1}
backend.username=${BACKEND_USERNAME:admin@school-admin.com}
backend.password=${BACKEND_PASSWORD:3OU4zn3q6Zh9}
